### ISSUE TITLE
Issue enabling plugin

### ISSUE THREAD

**Issue by rmdtech** [Tonnanto/BasicQuests#1]
[log.txt](https://github.com/Tonnanto/BasicQuests/files/5933621/log.txt)

Having issues enabling the plugin. Attached server log for reference. Config files are not created on initialisation for first time. Jar file present, but no other files created.

**Comment by Tonnanto** [comment]
It seems you are running a bukkit server.
A spigot compatible Server (Spigot or Paper) is required in order to run BasicQuests.

I'd always recommend switching to spigot or paper from bukkit / craftbukkit for performance reasons.
There should be no disadvantages or compatibility issues when switching.

Thanks for your feedback and sorry for the late reply :)
