### ISSUE TITLE
Color/message formatting

### ISSUE THREAD

**Issue by Log1x** [Tonnanto/BasicQuests#14]
Hey I really like your plugin.

I noticed all of the color formatting as well as various symbols and other formatting are hardcoded throughout the plugin. Are there any plans to make this more customizable? [Example](https://github.com/Tonnanto/BasicQuests/blob/main/src/main/java/de/stamme/basicquests/commands/QuestsCommand.java#L53)

A few libraries that can help achieve this are [MiniMessage](https://docs.adventure.kyori.net/minimessage/) and [MineDown](https://github.com/Phoenix616/MineDown). It would simplify a lot of the code when it comes to handling hovers, click events, and other message formatting as well.

MineDown is the simpler one to use and is what I use in all of my plugins, but MiniMessage is now built into Adventure (which is built into Paper) and is becoming a standard. Mind you, it'd still have to be shaded for Spigot support, though.

I wouldn't mind helping with this if you want to add me on Discord. Log1x#0001

**Comment by Tonnanto** [comment]
Thanks! I appreciate :)

Thats true... I haven't really touched the message formatting since the very first version of the plugin.
I had no specific plans on changing this. Mainly because I didn't know how. Your suggestions look like a good improvement tho.

Currently I don't have that much time to work on this plugin. Also I have some other thing on my todo list regarding BasicQuets. 
But I am very open to improvements and your contribution would be appreciated :)

Spigot Support is a must. Shading sounds acceptable :)
